version: "3"
services:
  app:
    build: ./app
    command: "tail -f /dev/null"
    volumes:
      - "./app:/app"
    ports:
      - "8080:80"
    env_file:
      - ".env"
  server:
    build: ./server
    command: "gunicorn --bind 0.0.0.0:80 wsgi:app"
    volumes:
      - "./server:/usr/src/server"
    ports:
      - "5000:80"
    depends_on:
      - redis
    env_file:
      - ".env"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ".env"