version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:80"
    env_file:
      - ".env"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5000:80"
    depends_on:
      - redis
    env_file:
      - ".env"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ".env"