version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:80"
    env_file:
      - ".env"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5000:80"
    env_file:
      - ".env"