version: "3"
services:
  app:
    build: ./app
    command: "npm run serve"
    ports:
      - "8080:8080"
    env_file:
      - ".env"
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - ".env"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ".env"