name: Build Development
on:
  workflow_dispatch:
  push:
    branches: ["development"]
jobs:
  build:
    runs-on: [self-hosted]
    environment: development
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: development

      # Builds the container images
      - shell: bash
        name: Container Build
        env:
          CI_SP_USER: ${{ secrets.CI_SP_USER }}
          CI_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
          CI_REGISTRY_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          CI_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          CI_ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
        run: |
          cd $GITHUB_WORKSPACE
          az cloud set --name AzureUSGovernment
          az login --service-principal -u $CI_SP_USER -p $CI_SP_PASSWORD --tenant $CI_SP_TENANT
          az account set --subscription $CI_ACR_SUBSCRIPTION
          az acr build --registry $CI_REGISTRY --image $CI_REGISTRY_PATH:vue-dev-$GITHUB_RUN_NUMBER --file app/Dockerfile app
          az acr build --registry $CI_REGISTRY --image $CI_REGISTRY_PATH:flask-dev-$GITHUB_RUN_NUMBER --file server/Dockerfile server
